language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: precise
      r: 3.2
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: openssl
      after_success: R -e 'covr::codecov()'
    - os: osx
      brew_packages: openssl@1.1
      before_install: brew uninstall --ignore-dependencies openssl
      env: PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
    - os: osx
      brew_packages: libressl
      before_install: brew uninstall --ignore-dependencies openssl openssl@1.1
      env: PKG_CONFIG_PATH="/usr/local/opt/libressl/lib/pkgconfig"
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
    - os: osx
      disable_homebrew: true

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libssl-dev
    - libsodium-dev

r_packages: covr

notifications:
  email:
    on_success: change
    on_failure: change
